spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT:5432}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate

jwt:
  secret: ${JWT_SECRET}
  access-token-ttl: 30m
  refresh-token-ttl: 14d

member-service:
  base-url: ${MEMBER_SERVICE_BASE_URL}
