server:
  port: 8080

spring:
  application:
    name: member-service
  profiles:
    active: local
  jackson:
    default-property-inclusion: non_null

springdoc:
  api-docs:
    path: /api/v1/members/api-docs
